### ISSUE TITLE
Link for each state not working

### ISSUE THREAD

**Issue by digillennial** [YMC-22/states-map#2]
Hello, I love the idea of this interactive map but is there a way to by pass the popup box and go from clicking on the state and taking the user to the desired link without clicking "read more"

I would like to include a link for each state to take people to different areas of the site.

![Screen Shot 2024-08-04 at 3 31 50 PM](https://github.com/user-attachments/assets/50c22c33-f618-44b7-8cf0-21a2b174bfca)

**Comment by YMC-22** [comment]
Hi!
The plugin works only by opening a pop-up window and then when you click on the button it is possible to go to the desired resource.

**Comment by digillennial** [comment]
Is there a way to bypass the popup and go straight to the desired link? Any code I can include into the plugin to make this work?
